## Numpy
* c 언어로 구현된 파이썬 라이브러리 
* 고성능의 수치 계산 수행
* Numerical Python 
* pandas, matplotlib 기반 
* 기본적으로 array라는 단위로 데이터 관리 

In [1]:
# 설치 방법
import numpy as np

In [3]:
# numpy#1, 2

'''
list (<-> array)ㅜ
array가 list보다 더 효율적인 연산이 가능한 형태 
'''
data1 = [1,2,3,4,5]
data2 = [1,2,3.5,4,5]

arr1 = np.array(data1)
print(arr1.shape)
print(arr1.dtype)

arr2 = np.array(data2)
print(arr2.shape)
print(arr2.dtype)

(5,)
int32
(5,)
float64


In [5]:
# numpy3
print(np.zeros(10))
print(np.zeros((3,5)))

print(np.ones(9))
print(np.ones((2,10)))

print(np.arange(10))
print(np.arange(3,10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]


In [6]:
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1.shape)

arr2 = np.array([[10,11,12],[13,14,15]])
print(arr2.shape)
print("====================")

print("+")
print(arr1 + arr2)
print("-")
print(arr1 - arr2)
print("*")
print(arr1 * arr2)
print("/")
print(arr1 / arr2)

(2, 3)
(2, 3)
+
[[11 13 15]
 [17 19 21]]
-
[[-9 -9 -9]
 [-9 -9 -9]]
*
[[10 22 36]
 [52 70 90]]
/
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]


In [7]:
arr1 = np.arange(10)
print(arr1[0])
print(arr1[4:])
print(arr1[-1])
print("=================")

arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2[2,3])
print(arr2[:,3])

0
[4 5 6 7 8 9]
9
12
[ 4  8 12]


In [8]:
#1~10 1씩 증가
arr1 = np.arange(1,11,1)
print(arr1)

#1~10 2씩 증가
arr2 = np.arange(1,11,2)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [10]:
# int random number
arr3 = np.random.randint(1, 11, size=5)
print(arr3)

arr4 = np.random.randint(1,11,size=(3,2))
print(arr4)

[ 2  1  1  9 10]
[[9 9]
 [5 2]
 [8 4]]


In [11]:
import numpy as np

print("rand")
print(np.random.rand(5))
print(np.random.rand(2,3))

print("randn")
print(np.random.randn(5))
print(np.random.randn(2,3))

print("choice")
print(np.random.choice([1,2,3,4,5],1))
print(np.random.choice(np.arange(1,11),5))

rand
[0.92274726 0.73572025 0.06578039 0.47477243 0.106921  ]
[[0.19428626 0.38492504 0.95649168]
 [0.93135686 0.9546575  0.15428816]]
randn
[-0.86008071 -0.52383662  0.51631481  0.50006435 -0.33981647]
[[-1.3934632  -1.43635835 -1.35424255]
 [ 0.07438047 -1.7719601  -0.39539805]]
choice
[5]
[2 1 4 5 9]


In [16]:
# numpy #8
a = np.array([[2,3,4],[5,4,7],[4,2,3]])

print("unique()🔽🔽🔽")
print(np.unique(a))

print("return_index=True🔽🔽🔽")
print(np.unique(a,return_index=True))

print("return_index=True 두 개의 값으로 나눠서 🔽🔽")
v, c = np.unique(a, return_index=True)
print(v)
print(c)

print("return_counts🔽🔽🔽")
print(np.unique(a, return_counts=True))

print("return_inverse🔽🔽🔽")
print(np.unique(a, return_inverse=True))

unique()🔽🔽🔽
[2 3 4 5 7]
return_index=True🔽🔽🔽
(array([2, 3, 4, 5, 7]), array([0, 1, 2, 3, 5], dtype=int64))
return_index=True 두 개의 값으로 나눠서 🔽🔽
[2 3 4 5 7]
[0 1 2 3 5]
return_counts🔽🔽🔽
(array([2, 3, 4, 5, 7]), array([2, 2, 3, 1, 1], dtype=int64))
return_inverse🔽🔽🔽
(array([2, 3, 4, 5, 7]), array([0, 1, 2, 3, 2, 4, 2, 0, 1], dtype=int64))


In [31]:

a = np.array([[2,3,2],[2,3,2],[4,2,3]])
print(np.unique(a, axis=0))

print("~~~~~~~~~~~~~~~~~~~~~")

b = np.array([[2,3,2],[2,3,2],[3,2,3]])
print(np.unique(b, axis=1))

[[2 3 2]
 [4 2 3]]
~~~~~~~~~~~~~~~~~~~~~
[[2 3]
 [2 3]
 [3 2]]


In [20]:
print("================== num10.py ==================")
v, c = np.unique([1,2,2,3,3,3,4,4,5], return_counts=True)
print(v)
print(c)

for i, j in zip(v,c):
    print(i,j)

================== num10.py ==================
[1 2 3 4 5]
[1 2 3 2 1]
1 1
2 2
3 3
4 2
5 1


In [28]:
arr1 = np.array([[11,22],
                 [33,44],
                 [55,66]])
print("arr1 🔽🔽🔽 \n",arr1)
print("arr1.size ==>",arr1.size)
print("arr1.shape ==>",arr1.shape)

# 전치행렬 
print("~~~~ transpose ~~~~~ ")
print("T 🔽🔽🔽 \n",arr1.T)
print("T.shape==>",arr1.T.shape)

arr1 🔽🔽🔽 
 [[11 22]
 [33 44]
 [55 66]]
arr1.size ==> 6
arr1.shape ==> (3, 2)
~~~~ transpose ~~~~~ 
T 🔽🔽🔽 
 [[11 33 55]
 [22 44 66]]
T.shape==> (2, 3)


In [29]:
arr1 = np.array([11,22,33,44,55])
print(arr1.dtype)

arr1 = arr1.astype(np.float32)
print(arr1.dtype)

arr2 = arr1.resize(3,2)
print(arr2)

arr3 = arr1.reshape(-1,2)
print(arr3)

int32
float32
None
[[11. 22.]
 [33. 44.]
 [55.  0.]]


In [36]:
# numpy#12
arr1 = np.array([11,22,33,44,55])
print(arr1.dtype)

arr1 = arr1.astype(np.float32)
print(arr1.dtype)

arr2 = arr1.resize(3,2)
print("resize ==> ",arr2)

arr3 = arr1.reshape(-1,2) 
# 행은 알아서 맞추면서 남은 공간은 0으로, 열은 2
print("reshape ==>\n ",arr3)

int32
float32
resize ==>  None
reshape ==>
  [[11. 22.]
 [33. 44.]
 [55.  0.]]


In [ ]:
import numpy as np

arr1 = np.array([11,22,33,44,55])
print(arr1)

arr2 = arr1[[True, True, False, True, False]]
print(arr2)

# boolean indexing
print(arr1 > 30)
print(arr1[arr1 > 30])

In [37]:
name = np.array(['홍길동','김철수','임꺽정','김철이','이활'])

for n in name:
    if '철' in n:
        print(n)

김철수
김철이
